remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Pouya change this
logo: /logo.png
description: Pouya write stuff here
show_downloads: true
google_analytics:
# theme: jekyll-theme-minimal
